# Use the official maven/Java 8
FROM maven:3.8.4-openjdk-17

WORKDIR /OnlineAuction
# Copy the pom.xml and src directory
COPY pom.xml .
COPY src ./src

RUN mvn clean install -DskipTests

EXPOSE 8080
CMD mvn spring-boot:run