@startuml

actor "User"
participant "createListing.html"
participant "AddWidgetController"
participant "MarketListing"
database "Database: MarketListing"

User -> createListing.html: auction starting price
createListing.html -> AddWidgetController: marketListing = new marketListing()
AddWidgetController -> MarketListing: model.addAttribute("auctionPrice",")
MarketListing -> MarketListing: setAuctionPrice(BigDecimal auctionPrice)
MarketListing -> "Database: MarketListing": save auctionPrice
createListing.html -> User: redirect to "/homepage"

@enduml