@startuml

actor User
participant "viewMarketListing.html"
participant "MarketListingDomainController"
database "Market_Listing"

User -> "viewMarketListing.html": enter your bid
"viewMarketListing.html" -> "MarketListingDomainController": MarketListing listing = marketRepository.findByID()
"MarketListingDomainController" -> "Market_Listing": marketRepository.save(listing)
"viewMarketListing.html" -> User: alert("Are you sure you want to place this bid?")
"viewMarketListing.html" -> User: redirect to viewMarketListing{listingID}

@enduml
