# From https://www.youtube.com/watch?v=BqCe-nSXSGI
name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "master" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file OnlineAuction/pom.xml -DskipTests

   
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: mvn --batch-mode --update-snapshots verify --file OnlineAuction/pom.xml
    - run: mkdir staging && cp OnlineAuction/target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

